name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Get App Access Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          permission-contents: write
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          repositories: plugins-dist
      - name: Checkout distribution repository
        uses: actions/checkout@v2
        with:
          repository: bs-community/plugins-dist
          path: '.dist'
          token: ${{ steps.app-token.outputs.token }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 8.15.9
      - name: Download nano
        run: ./download-nano.ps1
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./nano
        env:
          RUST_LOG: info
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: ./publish.ps1
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
